# Copyright (c) 2024 pytroll-image-comparison-tests developers
#
# This file is part of pytroll-image-comparison-tests.
#
# pytroll-image-comparison-tests is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# pytroll-image-comparison-tests is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# pytroll-image-comparison-tests.  If not, see <http://www.gnu.org/licenses/>.

from pytest import fixture
from unittest.mock import patch

@fixture
def fake_data():
    """Generate fake data as if it came from GitHub."""
    return {'action': 'submitted',
 'review': {'id': 2448307917,
  'node_id': 'PRR_kwDOAxBDEM6R7jbN',
  'user': {'login': 'gerritholl',
   'id': 500246,
   'node_id': 'MDQ6VXNlcjUwMDI0Ng==',
   'avatar_url': 'https://avatars.githubusercontent.com/u/500246?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/gerritholl',
   'html_url': 'https://github.com/gerritholl',
   'followers_url': 'https://api.github.com/users/gerritholl/followers',
   'following_url': 'https://api.github.com/users/gerritholl/following{/other_user}',
   'gists_url': 'https://api.github.com/users/gerritholl/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/gerritholl/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/gerritholl/subscriptions',
   'organizations_url': 'https://api.github.com/users/gerritholl/orgs',
   'repos_url': 'https://api.github.com/users/gerritholl/repos',
   'events_url': 'https://api.github.com/users/gerritholl/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/gerritholl/received_events',
   'type': 'User',
   'user_view_type': 'public',
   'site_admin': False},
  'body': 'start behave test',
  'commit_id': '4b6398b054c8cacb528a6171d3773bfc2f233cc2',
  'submitted_at': '2024-11-20T11:08:32Z',
  'state': 'commented',
  'html_url': 'https://github.com/pytroll/satpy/pull/2697#pullrequestreview-2448307917',
  'pull_request_url': 'https://api.github.com/repos/pytroll/satpy/pulls/2697',
  'author_association': 'MEMBER',
  '_links': {'html': {'href': 'https://github.com/pytroll/satpy/pull/2697#pullrequestreview-2448307917'},
   'pull_request': {'href': 'https://api.github.com/repos/pytroll/satpy/pulls/2697'}}},
 'pull_request': {'url': 'https://api.github.com/repos/pytroll/satpy/pulls/2697',
  'id': 1648131262,
  'node_id': 'PR_kwDOAxBDEM5iPHy-',
  'html_url': 'https://github.com/pytroll/satpy/pull/2697',
  'diff_url': 'https://github.com/pytroll/satpy/pull/2697.diff',
  'patch_url': 'https://github.com/pytroll/satpy/pull/2697.patch',
  'issue_url': 'https://api.github.com/repos/pytroll/satpy/issues/2697',
  'number': 2697,
  'state': 'open',
  'locked': False,
  'title': 'Experiments on a multi-file reader',
  'user': {'login': 'mraspaud',
   'id': 167802,
   'node_id': 'MDQ6VXNlcjE2NzgwMg==',
   'avatar_url': 'https://avatars.githubusercontent.com/u/167802?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/mraspaud',
   'html_url': 'https://github.com/mraspaud',
   'followers_url': 'https://api.github.com/users/mraspaud/followers',
   'following_url': 'https://api.github.com/users/mraspaud/following{/other_user}',
   'gists_url': 'https://api.github.com/users/mraspaud/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/mraspaud/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/mraspaud/subscriptions',
   'organizations_url': 'https://api.github.com/users/mraspaud/orgs',
   'repos_url': 'https://api.github.com/users/mraspaud/repos',
   'events_url': 'https://api.github.com/users/mraspaud/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/mraspaud/received_events',
   'type': 'User',
   'user_view_type': 'public',
   'site_admin': False},
  'body': '<!-- Describe what your PR does, and why -->\r\n<!-- For works in progress choose "Create draft pull request" from the drop-down green button. -->\r\n\r\n - [ ] Closes #2605  <!-- remove if there is no corresponding issue, which should only be the case for minor changes -->\r\n - [ ] Tests added <!-- for all bug fixes or enhancements -->\r\n - [ ] Fully documented <!-- remove if this change should not be visible to users, e.g., if it is an internal clean-up, or if this is part of a larger project that will be documented later -->\r\n - [ ] Add your name to `AUTHORS.md` if not there already\r\n',
  'created_at': '2023-12-18T09:23:33Z',
  'updated_at': '2024-11-20T11:08:32Z',
  'closed_at': None,
  'merged_at': None,
  'merge_commit_sha': None,
  'assignee': {'login': 'mraspaud',
   'id': 167802,
   'node_id': 'MDQ6VXNlcjE2NzgwMg==',
   'avatar_url': 'https://avatars.githubusercontent.com/u/167802?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/mraspaud',
   'html_url': 'https://github.com/mraspaud',
   'followers_url': 'https://api.github.com/users/mraspaud/followers',
   'following_url': 'https://api.github.com/users/mraspaud/following{/other_user}',
   'gists_url': 'https://api.github.com/users/mraspaud/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/mraspaud/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/mraspaud/subscriptions',
   'organizations_url': 'https://api.github.com/users/mraspaud/orgs',
   'repos_url': 'https://api.github.com/users/mraspaud/repos',
   'events_url': 'https://api.github.com/users/mraspaud/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/mraspaud/received_events',
   'type': 'User',
   'user_view_type': 'public',
   'site_admin': False},
  'assignees': [{'login': 'mraspaud',
    'id': 167802,
    'node_id': 'MDQ6VXNlcjE2NzgwMg==',
    'avatar_url': 'https://avatars.githubusercontent.com/u/167802?v=4',
    'gravatar_id': '',
    'url': 'https://api.github.com/users/mraspaud',
    'html_url': 'https://github.com/mraspaud',
    'followers_url': 'https://api.github.com/users/mraspaud/followers',
    'following_url': 'https://api.github.com/users/mraspaud/following{/other_user}',
    'gists_url': 'https://api.github.com/users/mraspaud/gists{/gist_id}',
    'starred_url': 'https://api.github.com/users/mraspaud/starred{/owner}{/repo}',
    'subscriptions_url': 'https://api.github.com/users/mraspaud/subscriptions',
    'organizations_url': 'https://api.github.com/users/mraspaud/orgs',
    'repos_url': 'https://api.github.com/users/mraspaud/repos',
    'events_url': 'https://api.github.com/users/mraspaud/events{/privacy}',
    'received_events_url': 'https://api.github.com/users/mraspaud/received_events',
    'type': 'User',
    'user_view_type': 'public',
    'site_admin': False}],
  'requested_reviewers': [],
  'requested_teams': [],
  'labels': [{'id': 323805264,
    'node_id': 'MDU6TGFiZWwzMjM4MDUyNjQ=',
    'url': 'https://api.github.com/repos/pytroll/satpy/labels/enhancement',
    'name': 'enhancement',
    'color': '84b6eb',
    'default': True,
    'description': 'code enhancements, features, improvements'},
   {'id': 841946101,
    'node_id': 'MDU6TGFiZWw4NDE5NDYxMDE=',
    'url': 'https://api.github.com/repos/pytroll/satpy/labels/component:readers',
    'name': 'component:readers',
    'color': '1d76db',
    'default': False,
    'description': None},
   {'id': 3049488993,
    'node_id': 'MDU6TGFiZWwzMDQ5NDg4OTkz',
    'url': 'https://api.github.com/repos/pytroll/satpy/labels/future%20ideas',
    'name': 'future ideas',
    'color': 'A2E2A9',
    'default': False,
    'description': 'Wishes and ideas for the future'}],
  'milestone': None,
  'draft': True,
  'commits_url': 'https://api.github.com/repos/pytroll/satpy/pulls/2697/commits',
  'review_comments_url': 'https://api.github.com/repos/pytroll/satpy/pulls/2697/comments',
  'review_comment_url': 'https://api.github.com/repos/pytroll/satpy/pulls/comments{/number}',
  'comments_url': 'https://api.github.com/repos/pytroll/satpy/issues/2697/comments',
  'statuses_url': 'https://api.github.com/repos/pytroll/satpy/statuses/4b6398b054c8cacb528a6171d3773bfc2f233cc2',
  'head': {'label': 'mraspaud:feature-multifile-handler',
   'ref': 'feature-multifile-handler',
   'sha': '4b6398b054c8cacb528a6171d3773bfc2f233cc2',
   'user': {'login': 'mraspaud',
    'id': 167802,
    'node_id': 'MDQ6VXNlcjE2NzgwMg==',
    'avatar_url': 'https://avatars.githubusercontent.com/u/167802?v=4',
    'gravatar_id': '',
    'url': 'https://api.github.com/users/mraspaud',
    'html_url': 'https://github.com/mraspaud',
    'followers_url': 'https://api.github.com/users/mraspaud/followers',
    'following_url': 'https://api.github.com/users/mraspaud/following{/other_user}',
    'gists_url': 'https://api.github.com/users/mraspaud/gists{/gist_id}',
    'starred_url': 'https://api.github.com/users/mraspaud/starred{/owner}{/repo}',
    'subscriptions_url': 'https://api.github.com/users/mraspaud/subscriptions',
    'organizations_url': 'https://api.github.com/users/mraspaud/orgs',
    'repos_url': 'https://api.github.com/users/mraspaud/repos',
    'events_url': 'https://api.github.com/users/mraspaud/events{/privacy}',
    'received_events_url': 'https://api.github.com/users/mraspaud/received_events',
    'type': 'User',
    'user_view_type': 'public',
    'site_admin': False},
   'repo': {'id': 153615929,
    'node_id': 'MDEwOlJlcG9zaXRvcnkxNTM2MTU5Mjk=',
    'name': 'satpy',
    'full_name': 'mraspaud/satpy',
    'private': False,
    'owner': {'login': 'mraspaud',
     'id': 167802,
     'node_id': 'MDQ6VXNlcjE2NzgwMg==',
     'avatar_url': 'https://avatars.githubusercontent.com/u/167802?v=4',
     'gravatar_id': '',
     'url': 'https://api.github.com/users/mraspaud',
     'html_url': 'https://github.com/mraspaud',
     'followers_url': 'https://api.github.com/users/mraspaud/followers',
     'following_url': 'https://api.github.com/users/mraspaud/following{/other_user}',
     'gists_url': 'https://api.github.com/users/mraspaud/gists{/gist_id}',
     'starred_url': 'https://api.github.com/users/mraspaud/starred{/owner}{/repo}',
     'subscriptions_url': 'https://api.github.com/users/mraspaud/subscriptions',
     'organizations_url': 'https://api.github.com/users/mraspaud/orgs',
     'repos_url': 'https://api.github.com/users/mraspaud/repos',
     'events_url': 'https://api.github.com/users/mraspaud/events{/privacy}',
     'received_events_url': 'https://api.github.com/users/mraspaud/received_events',
     'type': 'User',
     'user_view_type': 'public',
     'site_admin': False},
    'html_url': 'https://github.com/mraspaud/satpy',
    'description': 'Python package for earth-observing satellite data processing',
    'fork': True,
    'url': 'https://api.github.com/repos/mraspaud/satpy',
    'forks_url': 'https://api.github.com/repos/mraspaud/satpy/forks',
    'keys_url': 'https://api.github.com/repos/mraspaud/satpy/keys{/key_id}',
    'collaborators_url': 'https://api.github.com/repos/mraspaud/satpy/collaborators{/collaborator}',
    'teams_url': 'https://api.github.com/repos/mraspaud/satpy/teams',
    'hooks_url': 'https://api.github.com/repos/mraspaud/satpy/hooks',
    'issue_events_url': 'https://api.github.com/repos/mraspaud/satpy/issues/events{/number}',
    'events_url': 'https://api.github.com/repos/mraspaud/satpy/events',
    'assignees_url': 'https://api.github.com/repos/mraspaud/satpy/assignees{/user}',
    'branches_url': 'https://api.github.com/repos/mraspaud/satpy/branches{/branch}',
    'tags_url': 'https://api.github.com/repos/mraspaud/satpy/tags',
    'blobs_url': 'https://api.github.com/repos/mraspaud/satpy/git/blobs{/sha}',
    'git_tags_url': 'https://api.github.com/repos/mraspaud/satpy/git/tags{/sha}',
    'git_refs_url': 'https://api.github.com/repos/mraspaud/satpy/git/refs{/sha}',
    'trees_url': 'https://api.github.com/repos/mraspaud/satpy/git/trees{/sha}',
    'statuses_url': 'https://api.github.com/repos/mraspaud/satpy/statuses/{sha}',
    'languages_url': 'https://api.github.com/repos/mraspaud/satpy/languages',
    'stargazers_url': 'https://api.github.com/repos/mraspaud/satpy/stargazers',
    'contributors_url': 'https://api.github.com/repos/mraspaud/satpy/contributors',
    'subscribers_url': 'https://api.github.com/repos/mraspaud/satpy/subscribers',
    'subscription_url': 'https://api.github.com/repos/mraspaud/satpy/subscription',
    'commits_url': 'https://api.github.com/repos/mraspaud/satpy/commits{/sha}',
    'git_commits_url': 'https://api.github.com/repos/mraspaud/satpy/git/commits{/sha}',
    'comments_url': 'https://api.github.com/repos/mraspaud/satpy/comments{/number}',
    'issue_comment_url': 'https://api.github.com/repos/mraspaud/satpy/issues/comments{/number}',
    'contents_url': 'https://api.github.com/repos/mraspaud/satpy/contents/{+path}',
    'compare_url': 'https://api.github.com/repos/mraspaud/satpy/compare/{base}...{head}',
    'merges_url': 'https://api.github.com/repos/mraspaud/satpy/merges',
    'archive_url': 'https://api.github.com/repos/mraspaud/satpy/{archive_format}{/ref}',
    'downloads_url': 'https://api.github.com/repos/mraspaud/satpy/downloads',
    'issues_url': 'https://api.github.com/repos/mraspaud/satpy/issues{/number}',
    'pulls_url': 'https://api.github.com/repos/mraspaud/satpy/pulls{/number}',
    'milestones_url': 'https://api.github.com/repos/mraspaud/satpy/milestones{/number}',
    'notifications_url': 'https://api.github.com/repos/mraspaud/satpy/notifications{?since,all,participating}',
    'labels_url': 'https://api.github.com/repos/mraspaud/satpy/labels{/name}',
    'releases_url': 'https://api.github.com/repos/mraspaud/satpy/releases{/id}',
    'deployments_url': 'https://api.github.com/repos/mraspaud/satpy/deployments',
    'created_at': '2018-10-18T11:53:39Z',
    'updated_at': '2024-01-25T13:49:37Z',
    'pushed_at': '2024-11-13T10:09:25Z',
    'git_url': 'git://github.com/mraspaud/satpy.git',
    'ssh_url': 'git@github.com:mraspaud/satpy.git',
    'clone_url': 'https://github.com/mraspaud/satpy.git',
    'svn_url': 'https://github.com/mraspaud/satpy',
    'homepage': 'http://satpy.readthedocs.org/en/latest/',
    'size': 32707,
    'stargazers_count': 4,
    'watchers_count': 4,
    'language': 'Python',
    'has_issues': False,
    'has_projects': True,
    'has_downloads': True,
    'has_wiki': True,
    'has_pages': True,
    'has_discussions': False,
    'forks_count': 0,
    'mirror_url': None,
    'archived': False,
    'disabled': False,
    'open_issues_count': 0,
    'license': {'key': 'gpl-3.0',
     'name': 'GNU General Public License v3.0',
     'spdx_id': 'GPL-3.0',
     'url': 'https://api.github.com/licenses/gpl-3.0',
     'node_id': 'MDc6TGljZW5zZTk='},
    'allow_forking': True,
    'is_template': False,
    'web_commit_signoff_required': False,
    'topics': [],
    'visibility': 'public',
    'forks': 0,
    'open_issues': 0,
    'watchers': 4,
    'default_branch': 'master',
    'allow_squash_merge': True,
    'allow_merge_commit': True,
    'allow_rebase_merge': True,
    'allow_auto_merge': False,
    'delete_branch_on_merge': False,
    'allow_update_branch': False,
    'use_squash_pr_title_as_default': False,
    'squash_merge_commit_message': 'COMMIT_MESSAGES',
    'squash_merge_commit_title': 'COMMIT_OR_PR_TITLE',
    'merge_commit_message': 'PR_TITLE',
    'merge_commit_title': 'MERGE_MESSAGE'}},
  'base': {'label': 'pytroll:main',
   'ref': 'main',
   'sha': 'e20ea4182a0cf14791e40e9886c9724167f49920',
   'user': {'login': 'pytroll',
    'id': 13004956,
    'node_id': 'MDEyOk9yZ2FuaXphdGlvbjEzMDA0OTU2',
    'avatar_url': 'https://avatars.githubusercontent.com/u/13004956?v=4',
    'gravatar_id': '',
    'url': 'https://api.github.com/users/pytroll',
    'html_url': 'https://github.com/pytroll',
    'followers_url': 'https://api.github.com/users/pytroll/followers',
    'following_url': 'https://api.github.com/users/pytroll/following{/other_user}',
    'gists_url': 'https://api.github.com/users/pytroll/gists{/gist_id}',
    'starred_url': 'https://api.github.com/users/pytroll/starred{/owner}{/repo}',
    'subscriptions_url': 'https://api.github.com/users/pytroll/subscriptions',
    'organizations_url': 'https://api.github.com/users/pytroll/orgs',
    'repos_url': 'https://api.github.com/users/pytroll/repos',
    'events_url': 'https://api.github.com/users/pytroll/events{/privacy}',
    'received_events_url': 'https://api.github.com/users/pytroll/received_events',
    'type': 'Organization',
    'user_view_type': 'public',
    'site_admin': False},
   'repo': {'id': 51397392,
    'node_id': 'MDEwOlJlcG9zaXRvcnk1MTM5NzM5Mg==',
    'name': 'satpy',
    'full_name': 'pytroll/satpy',
    'private': False,
    'owner': {'login': 'pytroll',
     'id': 13004956,
     'node_id': 'MDEyOk9yZ2FuaXphdGlvbjEzMDA0OTU2',
     'avatar_url': 'https://avatars.githubusercontent.com/u/13004956?v=4',
     'gravatar_id': '',
     'url': 'https://api.github.com/users/pytroll',
     'html_url': 'https://github.com/pytroll',
     'followers_url': 'https://api.github.com/users/pytroll/followers',
     'following_url': 'https://api.github.com/users/pytroll/following{/other_user}',
     'gists_url': 'https://api.github.com/users/pytroll/gists{/gist_id}',
     'starred_url': 'https://api.github.com/users/pytroll/starred{/owner}{/repo}',
     'subscriptions_url': 'https://api.github.com/users/pytroll/subscriptions',
     'organizations_url': 'https://api.github.com/users/pytroll/orgs',
     'repos_url': 'https://api.github.com/users/pytroll/repos',
     'events_url': 'https://api.github.com/users/pytroll/events{/privacy}',
     'received_events_url': 'https://api.github.com/users/pytroll/received_events',
     'type': 'Organization',
     'user_view_type': 'public',
     'site_admin': False},
    'html_url': 'https://github.com/pytroll/satpy',
    'description': 'Python package for earth-observing satellite data processing',
    'fork': False,
    'url': 'https://api.github.com/repos/pytroll/satpy',
    'forks_url': 'https://api.github.com/repos/pytroll/satpy/forks',
    'keys_url': 'https://api.github.com/repos/pytroll/satpy/keys{/key_id}',
    'collaborators_url': 'https://api.github.com/repos/pytroll/satpy/collaborators{/collaborator}',
    'teams_url': 'https://api.github.com/repos/pytroll/satpy/teams',
    'hooks_url': 'https://api.github.com/repos/pytroll/satpy/hooks',
    'issue_events_url': 'https://api.github.com/repos/pytroll/satpy/issues/events{/number}',
    'events_url': 'https://api.github.com/repos/pytroll/satpy/events',
    'assignees_url': 'https://api.github.com/repos/pytroll/satpy/assignees{/user}',
    'branches_url': 'https://api.github.com/repos/pytroll/satpy/branches{/branch}',
    'tags_url': 'https://api.github.com/repos/pytroll/satpy/tags',
    'blobs_url': 'https://api.github.com/repos/pytroll/satpy/git/blobs{/sha}',
    'git_tags_url': 'https://api.github.com/repos/pytroll/satpy/git/tags{/sha}',
    'git_refs_url': 'https://api.github.com/repos/pytroll/satpy/git/refs{/sha}',
    'trees_url': 'https://api.github.com/repos/pytroll/satpy/git/trees{/sha}',
    'statuses_url': 'https://api.github.com/repos/pytroll/satpy/statuses/{sha}',
    'languages_url': 'https://api.github.com/repos/pytroll/satpy/languages',
    'stargazers_url': 'https://api.github.com/repos/pytroll/satpy/stargazers',
    'contributors_url': 'https://api.github.com/repos/pytroll/satpy/contributors',
    'subscribers_url': 'https://api.github.com/repos/pytroll/satpy/subscribers',
    'subscription_url': 'https://api.github.com/repos/pytroll/satpy/subscription',
    'commits_url': 'https://api.github.com/repos/pytroll/satpy/commits{/sha}',
    'git_commits_url': 'https://api.github.com/repos/pytroll/satpy/git/commits{/sha}',
    'comments_url': 'https://api.github.com/repos/pytroll/satpy/comments{/number}',
    'issue_comment_url': 'https://api.github.com/repos/pytroll/satpy/issues/comments{/number}',
    'contents_url': 'https://api.github.com/repos/pytroll/satpy/contents/{+path}',
    'compare_url': 'https://api.github.com/repos/pytroll/satpy/compare/{base}...{head}',
    'merges_url': 'https://api.github.com/repos/pytroll/satpy/merges',
    'archive_url': 'https://api.github.com/repos/pytroll/satpy/{archive_format}{/ref}',
    'downloads_url': 'https://api.github.com/repos/pytroll/satpy/downloads',
    'issues_url': 'https://api.github.com/repos/pytroll/satpy/issues{/number}',
    'pulls_url': 'https://api.github.com/repos/pytroll/satpy/pulls{/number}',
    'milestones_url': 'https://api.github.com/repos/pytroll/satpy/milestones{/number}',
    'notifications_url': 'https://api.github.com/repos/pytroll/satpy/notifications{?since,all,participating}',
    'labels_url': 'https://api.github.com/repos/pytroll/satpy/labels{/name}',
    'releases_url': 'https://api.github.com/repos/pytroll/satpy/releases{/id}',
    'deployments_url': 'https://api.github.com/repos/pytroll/satpy/deployments',
    'created_at': '2016-02-09T20:29:43Z',
    'updated_at': '2024-11-20T09:51:12Z',
    'pushed_at': '2024-11-20T10:54:52Z',
    'git_url': 'git://github.com/pytroll/satpy.git',
    'ssh_url': 'git@github.com:pytroll/satpy.git',
    'clone_url': 'https://github.com/pytroll/satpy.git',
    'svn_url': 'https://github.com/pytroll/satpy',
    'homepage': 'http://satpy.readthedocs.org/en/latest/',
    'size': 23448,
    'stargazers_count': 1074,
    'watchers_count': 1074,
    'language': 'Python',
    'has_issues': True,
    'has_projects': True,
    'has_downloads': True,
    'has_wiki': True,
    'has_pages': False,
    'has_discussions': False,
    'forks_count': 298,
    'mirror_url': None,
    'archived': False,
    'disabled': False,
    'open_issues_count': 506,
    'license': {'key': 'gpl-3.0',
     'name': 'GNU General Public License v3.0',
     'spdx_id': 'GPL-3.0',
     'url': 'https://api.github.com/licenses/gpl-3.0',
     'node_id': 'MDc6TGljZW5zZTk='},
    'allow_forking': True,
    'is_template': False,
    'web_commit_signoff_required': False,
    'topics': ['closember',
     'dask',
     'hacktoberfest',
     'python',
     'satellite',
     'weather',
     'xarray'],
    'visibility': 'public',
    'forks': 298,
    'open_issues': 506,
    'watchers': 1074,
    'default_branch': 'main',
    'allow_squash_merge': True,
    'allow_merge_commit': True,
    'allow_rebase_merge': True,
    'allow_auto_merge': False,
    'delete_branch_on_merge': False,
    'allow_update_branch': False,
    'use_squash_pr_title_as_default': False,
    'squash_merge_commit_message': 'COMMIT_MESSAGES',
    'squash_merge_commit_title': 'COMMIT_OR_PR_TITLE',
    'merge_commit_message': 'PR_TITLE',
    'merge_commit_title': 'MERGE_MESSAGE'}},
  '_links': {'self': {'href': 'https://api.github.com/repos/pytroll/satpy/pulls/2697'},
   'html': {'href': 'https://github.com/pytroll/satpy/pull/2697'},
   'issue': {'href': 'https://api.github.com/repos/pytroll/satpy/issues/2697'},
   'comments': {'href': 'https://api.github.com/repos/pytroll/satpy/issues/2697/comments'},
   'review_comments': {'href': 'https://api.github.com/repos/pytroll/satpy/pulls/2697/comments'},
   'review_comment': {'href': 'https://api.github.com/repos/pytroll/satpy/pulls/comments{/number}'},
   'commits': {'href': 'https://api.github.com/repos/pytroll/satpy/pulls/2697/commits'},
   'statuses': {'href': 'https://api.github.com/repos/pytroll/satpy/statuses/4b6398b054c8cacb528a6171d3773bfc2f233cc2'}},
  'author_association': 'MEMBER',
  'auto_merge': None,
  'active_lock_reason': None},
 'repository': {'id': 51397392,
  'node_id': 'MDEwOlJlcG9zaXRvcnk1MTM5NzM5Mg==',
  'name': 'satpy',
  'full_name': 'pytroll/satpy',
  'private': False,
  'owner': {'login': 'pytroll',
   'id': 13004956,
   'node_id': 'MDEyOk9yZ2FuaXphdGlvbjEzMDA0OTU2',
   'avatar_url': 'https://avatars.githubusercontent.com/u/13004956?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/pytroll',
   'html_url': 'https://github.com/pytroll',
   'followers_url': 'https://api.github.com/users/pytroll/followers',
   'following_url': 'https://api.github.com/users/pytroll/following{/other_user}',
   'gists_url': 'https://api.github.com/users/pytroll/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/pytroll/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/pytroll/subscriptions',
   'organizations_url': 'https://api.github.com/users/pytroll/orgs',
   'repos_url': 'https://api.github.com/users/pytroll/repos',
   'events_url': 'https://api.github.com/users/pytroll/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/pytroll/received_events',
   'type': 'Organization',
   'user_view_type': 'public',
   'site_admin': False},
  'html_url': 'https://github.com/pytroll/satpy',
  'description': 'Python package for earth-observing satellite data processing',
  'fork': False,
  'url': 'https://api.github.com/repos/pytroll/satpy',
  'forks_url': 'https://api.github.com/repos/pytroll/satpy/forks',
  'keys_url': 'https://api.github.com/repos/pytroll/satpy/keys{/key_id}',
  'collaborators_url': 'https://api.github.com/repos/pytroll/satpy/collaborators{/collaborator}',
  'teams_url': 'https://api.github.com/repos/pytroll/satpy/teams',
  'hooks_url': 'https://api.github.com/repos/pytroll/satpy/hooks',
  'issue_events_url': 'https://api.github.com/repos/pytroll/satpy/issues/events{/number}',
  'events_url': 'https://api.github.com/repos/pytroll/satpy/events',
  'assignees_url': 'https://api.github.com/repos/pytroll/satpy/assignees{/user}',
  'branches_url': 'https://api.github.com/repos/pytroll/satpy/branches{/branch}',
  'tags_url': 'https://api.github.com/repos/pytroll/satpy/tags',
  'blobs_url': 'https://api.github.com/repos/pytroll/satpy/git/blobs{/sha}',
  'git_tags_url': 'https://api.github.com/repos/pytroll/satpy/git/tags{/sha}',
  'git_refs_url': 'https://api.github.com/repos/pytroll/satpy/git/refs{/sha}',
  'trees_url': 'https://api.github.com/repos/pytroll/satpy/git/trees{/sha}',
  'statuses_url': 'https://api.github.com/repos/pytroll/satpy/statuses/{sha}',
  'languages_url': 'https://api.github.com/repos/pytroll/satpy/languages',
  'stargazers_url': 'https://api.github.com/repos/pytroll/satpy/stargazers',
  'contributors_url': 'https://api.github.com/repos/pytroll/satpy/contributors',
  'subscribers_url': 'https://api.github.com/repos/pytroll/satpy/subscribers',
  'subscription_url': 'https://api.github.com/repos/pytroll/satpy/subscription',
  'commits_url': 'https://api.github.com/repos/pytroll/satpy/commits{/sha}',
  'git_commits_url': 'https://api.github.com/repos/pytroll/satpy/git/commits{/sha}',
  'comments_url': 'https://api.github.com/repos/pytroll/satpy/comments{/number}',
  'issue_comment_url': 'https://api.github.com/repos/pytroll/satpy/issues/comments{/number}',
  'contents_url': 'https://api.github.com/repos/pytroll/satpy/contents/{+path}',
  'compare_url': 'https://api.github.com/repos/pytroll/satpy/compare/{base}...{head}',
  'merges_url': 'https://api.github.com/repos/pytroll/satpy/merges',
  'archive_url': 'https://api.github.com/repos/pytroll/satpy/{archive_format}{/ref}',
  'downloads_url': 'https://api.github.com/repos/pytroll/satpy/downloads',
  'issues_url': 'https://api.github.com/repos/pytroll/satpy/issues{/number}',
  'pulls_url': 'https://api.github.com/repos/pytroll/satpy/pulls{/number}',
  'milestones_url': 'https://api.github.com/repos/pytroll/satpy/milestones{/number}',
  'notifications_url': 'https://api.github.com/repos/pytroll/satpy/notifications{?since,all,participating}',
  'labels_url': 'https://api.github.com/repos/pytroll/satpy/labels{/name}',
  'releases_url': 'https://api.github.com/repos/pytroll/satpy/releases{/id}',
  'deployments_url': 'https://api.github.com/repos/pytroll/satpy/deployments',
  'created_at': '2016-02-09T20:29:43Z',
  'updated_at': '2024-11-20T09:51:12Z',
  'pushed_at': '2024-11-20T10:54:52Z',
  'git_url': 'git://github.com/pytroll/satpy.git',
  'ssh_url': 'git@github.com:pytroll/satpy.git',
  'clone_url': 'https://github.com/pytroll/satpy.git',
  'svn_url': 'https://github.com/pytroll/satpy',
  'homepage': 'http://satpy.readthedocs.org/en/latest/',
  'size': 23448,
  'stargazers_count': 1074,
  'watchers_count': 1074,
  'language': 'Python',
  'has_issues': True,
  'has_projects': True,
  'has_downloads': True,
  'has_wiki': True,
  'has_pages': False,
  'has_discussions': False,
  'forks_count': 298,
  'mirror_url': None,
  'archived': False,
  'disabled': False,
  'open_issues_count': 506,
  'license': {'key': 'gpl-3.0',
   'name': 'GNU General Public License v3.0',
   'spdx_id': 'GPL-3.0',
   'url': 'https://api.github.com/licenses/gpl-3.0',
   'node_id': 'MDc6TGljZW5zZTk='},
  'allow_forking': True,
  'is_template': False,
  'web_commit_signoff_required': False,
  'topics': ['closember',
   'dask',
   'hacktoberfest',
   'python',
   'satellite',
   'weather',
   'xarray'],
  'visibility': 'public',
  'forks': 298,
  'open_issues': 506,
  'watchers': 1074,
  'default_branch': 'main',
  'custom_properties': {}},
 'organization': {'login': 'pytroll',
  'id': 13004956,
  'node_id': 'MDEyOk9yZ2FuaXphdGlvbjEzMDA0OTU2',
  'url': 'https://api.github.com/orgs/pytroll',
  'repos_url': 'https://api.github.com/orgs/pytroll/repos',
  'events_url': 'https://api.github.com/orgs/pytroll/events',
  'hooks_url': 'https://api.github.com/orgs/pytroll/hooks',
  'issues_url': 'https://api.github.com/orgs/pytroll/issues',
  'members_url': 'https://api.github.com/orgs/pytroll/members{/member}',
  'public_members_url': 'https://api.github.com/orgs/pytroll/public_members{/member}',
  'avatar_url': 'https://avatars.githubusercontent.com/u/13004956?v=4',
  'description': ''},
 'sender': {'login': 'gerritholl',
  'id': 500246,
  'node_id': 'MDQ6VXNlcjUwMDI0Ng==',
  'avatar_url': 'https://avatars.githubusercontent.com/u/500246?v=4',
  'gravatar_id': '',
  'url': 'https://api.github.com/users/gerritholl',
  'html_url': 'https://github.com/gerritholl',
  'followers_url': 'https://api.github.com/users/gerritholl/followers',
  'following_url': 'https://api.github.com/users/gerritholl/following{/other_user}',
  'gists_url': 'https://api.github.com/users/gerritholl/gists{/gist_id}',
  'starred_url': 'https://api.github.com/users/gerritholl/starred{/owner}{/repo}',
  'subscriptions_url': 'https://api.github.com/users/gerritholl/subscriptions',
  'organizations_url': 'https://api.github.com/users/gerritholl/orgs',
  'repos_url': 'https://api.github.com/users/gerritholl/repos',
  'events_url': 'https://api.github.com/users/gerritholl/events{/privacy}',
  'received_events_url': 'https://api.github.com/users/gerritholl/received_events',
  'type': 'User',
  'user_view_type': 'public',
  'site_admin': False}}

@patch("requests.post")
def test_post_comment(rp):
    """Test posting comments."""
    from serverLogic.api_utils import post_github_comment
    post_github_comment("dummy_repo", 0, "dummy comment", "dummy_token")
    rp.assert_called_with(
        "https://api.github.com/repos/dummy_repo/issues/0/comments",
        headers={"Authorization": "token dummy_token",
                 "Accept": "application/vnd.github.v3+json"},
        json = {"body": "dummy comment"})

def test_extract_pr_info(fake_data):
    from serverLogic.api_utils import extract_pull_request_info
    assert extract_pull_request_info(fake_data) == (
            "pytroll/satpy",
            "https://github.com/mraspaud/satpy.git",
            "feature-multifile-handler",
            2697)

@patch("requests.get")
def test_validate_user(rp, fake_data):
    from serverLogic.api_utils import validate_user
    validate_user(fake_data, "dummy_token")
    rp.assert_called_with(
        "https://api.github.com/orgs/pytroll/members/gerritholl",
        headers={"Authorization": "token dummy_token",
                 "Accept": "application/vnd.github.v3+json"})
