---
- name: Copy serverLogic directory to the server
  ansible.builtin.copy:
    src: "{{ host_path }}/image-comparison-tests-dev/serverLogic/"
    # src: "../serverLogic/"
    dest: /home/{{ comparison_user }}/pytroll-image-comparison-tests/serverLogic/
    owner: "{{ comparison_user }}"
    group: "{{ comparison_user }}"
    mode: '0775'

- name: Convert Windows line endings to Unix line endings
  ansible.builtin.replace:
    path: /home/{{ comparison_user }}/pytroll-image-comparison-tests/serverLogic/start_server.sh
    regexp: '\r'
    replace: ''
  become: yes

- name: Copy data directory to the server
  ansible.builtin.copy:
    src: "{{ host_path }}/image-comparison-tests-dev/data/"
    dest: /home/{{ comparison_user }}/pytroll-image-comparison-tests/data/
    owner: "{{ comparison_user }}"
    group: "{{ comparison_user }}"
    mode: '0775'

- name: Set permissions
  ansible.builtin.file:
    path: /home/{{ comparison_user }}/
    owner: "{{ comparison_user }}"
    group: "{{ comparison_user }}"
    mode: '0775'
    recurse: yes
