---
- name: Install base packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - python3-pip
    - python3-gdal
    - virtualenv
  become: yes

- name: Check if Docker GPG key is already added
  shell: apt-key list | grep -i docker || true
  register: docker_gpg_check
  changed_when: false

- name: Add Docker GPG key if not already added
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  when: docker_gpg_check.stdout == ""
  become: yes

- name: Check if Docker repository is already added
  shell: grep -r "download.docker.com/linux/ubuntu" /etc/apt/sources.list /etc/apt/sources.list.d/ || true
  register: docker_repo_check
  changed_when: false

- name: Add Docker repository if not already added
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
  when: docker_repo_check.stdout == ""
  become: yes

- name: Install Docker packages
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: yes
  become: yes

- name: Ensure Docker service is started and enabled
  systemd:
    name: docker
    enabled: yes
    state: started
  become: yes

- name: Add user to docker group
  user:
    name: "{{ comparison_user }}"
    groups: docker
    append: yes
  become: yes

- name: Install packages used for image-comparison service
  pip:
    name:
      - fastapi
      - requests
      - flask
      - werkzeug
      - python-dotenv
      - gunicorn
      - docker
    virtualenv: /home/{{ comparison_user }}/venv/
  become: yes

- name: Change permissions of /home/{{ comparison_user }}/venv directory
  ansible.builtin.file:
    path: /home/{{ comparison_user }}/venv
    recurse: yes
    owner: "{{ comparison_user }}"
    group: "{{ comparison_user }}"
  become: yes
